import { Toaster } from "react-hot-toast";
import "./globals.css";
import NavBar from "@/components/navbar/Navbar";
import { SessionProvider } from "@/context/SessionContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>BoardSphere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="bg-black">
        <SessionProvider>
          <NavBar />
          <Toaster />
          <main className="w-full min-h-screen z-10">{children}</main>
          <div id="portal"></div>
        </SessionProvider>
      </body>
    </html>
  );
}
